### ISSUE TITLE
Suggestions close doesn't play when exiting settings.

### ISSUE THREAD

**Issue by derekriemer** [josephsl/wintenApps#5] opened 2016-08-28 07:01 UTC
1. open settings.
2. type "account"
3. wait for the zoop sound.
4. alt+f4.
   What should happen? Suggestions closed (reverse xoop sound). No sound is played.

**Comment by josephsl** [comment] 2016-08-29 18:09
Hi,

Confirmed. This is because Controller For event isn't fired when the app exits (technically, when it enters suspended state).

Thanks.

**Comment by josephsl** [comment] 2021-05-30 06:05
Hi,

Still the case in 2021, although there's relaly nothing we can do about this. Closing.

**Closed by josephsl** 2021-05-30 06:05 UTC
